export const DELETE_CART='DELETE_CART';
export const DELETE_CART_SUCCESS='DELETE_CART_SUCCESS';


export const UPDATE_CART_INCREASE='UPDATE_CART_INCREASE';
export const UPDATE_CART_INCREASE_SUCCESS='UPDATE_CART_INCREASE_SUCCESS';


export const UPDATE_CART_REDUCTION='UPDATE_CART_REDUCTION';
export const UPDATE_CART_REDUCTION_SUCCESS='UPDATE_CART_REDUCTION_SUCCESS';


// export const DELETE_CART='DELETE_CART';
// export const DELETE_CART_SUCCESS='DELETE_CART_SUCCESS';